### ISSUE TITLE
Fontawesom

### ISSUE THREAD

**Issue by simonasablinaite** [practical-projects/shuffle-project#1]
- [ ] Download fontaweson file;
- [ ] Unzip it;
- [ ] Delete unnecessary files, create and adjust necessary ones;

**Comment by simonasablinaite** [comment]
Bent aš naudoju tą, kur iš Rimanto išmokau, tai nežinau, jei nieko papildomai nebereikia daryti, gal tada bandom jį🤔🙂

**Comment by sauliusss** [comment]
Rimantas sake, kad jie nieko nesiskiria, lyg ir, man pvz paprasciau, nes nereikia ieskoti failu ar folderiu, ten keist lokacijas, o cia tiesiog, imeti css linka ir turetu veikt

**Comment by simonasablinaite** [comment]
Tai viskas ok :)

**Comment by simonasablinaite** [comment]
If you task is done and pull request is done you need to delete the branch "fontawesome" ;)
